#ifndef MATRIX_MULTIPLICATION_THREADS_CONSTANTS_H
#define MATRIX_MULTIPLICATION_THREADS_CONSTANTS_H

#define MAX_FILE_NAME_SIZE 33

#define MAX_THREADS 30549


#endif //MATRIX_MULTIPLICATION_THREADS_CONSTANTS_H
